import Head from "next/head";
import { MainLayout } from "@components/templates";
import { BlogsWithPagination } from "@features/blogs";

export default function Blog() {
	return (
		<>
			<Head>
				<title>Social brothers</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
				<BlogsWithPagination />
			</MainLayout>
		</>
	);
}
